name: Pull request of code to master

on:
  pull_request:
    branches: master
    types: [opened, synchronize, reopened, labeled]
    paths:
    - 'src/**'

jobs:
  label:
    name: "Check labels"
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 1
          labels: "patch, minor, major"
