name: PR code to master

on:
  pull_request:
    branches: master
    types: [opened, synchronize, reopened, labeled]

jobs:
  Check_source_branch:
    name: "Check does changes contain code"
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2.2.0
        id: filter
        with:
          filters: |
            code:
              - 'src/**'
      - if: steps.filter.outputs.code == "true"
        uses: Thog/action-equals@v1
        id: head_branch
        with:
          a: ${{ github.event.pull_request.head.ref }}
          b: "release"
      - if: steps.filter.outputs.code == "true"
        name: "Check equal result"
        run: |
          if [[ "${{ steps.head_branch.outputs.result }}" != "true" ]];
          then
            echo "Wrong head branch, should be release"
            exit 4
          fi
      - if: steps.filter.outputs.code == "false"
        name: "Feedback changes doesn't contain code"
        run: echo "Changes doesn't contain code"
  Check_version:
    needs: Check_source_branch
    name: "Check version"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Get last release tag"
        id: last_release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: InsonusK/GitHubReleaseTemplate
      - name: "Get current version of package"
        run: |
          file=`cat src/SomeAwesomeProject/SomeAwesomeProject.csproj`
          version=$(grep -oPm1 "(?<=<PackageVersion>)[^<]+" <<< $file)
          version=v${version}
          echo $version
          echo '::set-env name=VERSION::'${version}
      - name: "Print current version"
        run: |
          echo "${{ env.VERSION }}"
      - uses: Thog/action-equals@v1
        id: version_compare
        with:
          a: ${{ env.VERSION }}
          b: ${{ steps.last_release.outputs.release }}
      - name: "Check equal result"
        run: |
          if [[ "${{ steps.version_compare.outputs.result }}" != "true" ]];
          then
            echo "Drawft release doesn't equal project version"
            exit 4
          fi
