name: PR to master

on:
  pull_request:
    branches: master
    types: [opened, synchronize, reopened, labeled]

jobs:
  Check_version:
    name: "Check version"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Get last release tag"
        id: last_release
        uses: pozetroninc/github-action-get-latest-release@master
      - name: "Get current version of package"
        run: |
          file=`cat src/SomeAwesomeProject/SomeAwesomeProject.csproj`
          version=$(grep -oPm1 "(?<=<PackageVersion>)[^<]+" <<< $file)
          version=v${version}
          echo $version
          echo '::set-env name=VERSION::'${version}
      - name: "Print current version"
        run: |
          echo "${{ env.VERSION }}"

      - uses: Thog/action-equals@v1
        with:
          a: ${{ env.VERSION }}
          b: ${{ steps.last_release.outputs.release }}
