name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - release

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Print new release version"
        run: |
          echo "${{ steps.release.outputs.tag_name }}"

