name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - release

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Print new release version"
        run: |
          echo "${{ steps.release.outputs.tag_name }}"
          draft_version=${{ steps.release.outputs.tag_name }}
          echo ${draft_version}
          echo '::set-env name=DRAFT_VERSION::'${draft_version:1}
      - name: "Print new release version(env)"
        run: |
          echo "${{ env.DRAFT_VERSION }}"
      - uses: actions/checkout@v2
      - name: "Get current version of package"
        run: |
          file=`cat src/SomeAwesomeProject/SomeAwesomeProject.csproj`
          version=$(grep -oPm1 "(?<=<PackageVersion>)[^<]+" <<< $file)
          echo $version
          echo '::set-env name=VERSION::'${version}
      - name: "Print current version"
        run: |
          echo "${{ env.VERSION }}"

